{
 "title": "Deutexrium",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "erlang_vm_memory_bytes_total", "legendFormat": "{{kind}}" },
    {
     "expr": "sum(erlang_vm_memory_bytes_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deutex_data_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "erlang_vm_statistics_bytes_output_total",
     "legendFormat": "sent"
    },
    {
     "expr": "erlang_vm_statistics_bytes_received_total",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Processes and ports",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deutex_processes", "legendFormat": "processes" },
    { "expr": "deutex_ports", "legendFormat": "ports" }
   ]
  },
  {
   "title": "RAM details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "erlang_vm_memory_processes_bytes_total{usage=\"used\"}",
     "legendFormat": "process"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total",
     "legendFormat": "{{usage}}"
    }
   ]
  },
  { "title": "Command latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "/meme",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "deutex_cmd_execute_bucket{command=\"meme\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "/generate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "deutex_cmd_execute_bucket{command=\"generate\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "/generate_from",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "deutex_cmd_execute_bucket{command=\"generate_from\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Generate by them",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "deutex_cmd_execute_bucket{command=\"gen_by_them\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unimportant command latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "deutex_cmd_execute_sum{command=~\"donate|first_time_setup|help|privacy|scoreboard|settings|stats|status|support\"}\n/ deutex_cmd_execute_count{command=~\"donate|first_time_setup|help|privacy|scoreboard|settings|stats|status|support\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Important command latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "deutex_cmd_execute_sum{command=~\"gen_by_them|gen_global|generate_from|generate|impostor|meme|pre_train|reset\"}\n/ deutex_cmd_execute_count{command=~\"gen_by_them|gen_global|generate_from|generate|impostor|meme|pre_train|reset\"}",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}